# GitHub Pages set-up file..
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: soz-live
description: A CAD extension, written in Lisp
show_downloads: false
google_analytics:
